### ISSUE TITLE
[FR]: トップ画像の修正

### ISSUE THREAD

**Issue by fcabs84** [fcpuentet/fcpuentet-frontend#279]
### 既存の課題がありませんか？

- [X] 既存の課題を検索してみました

### 問題を説明する

ページを表示したときトップ画像のみの表示になっているが、瞬時に最新情報が目に入るようお知らせスライドを同時に表示させたい。

### 解決策を説明する

- トップ画像は既存の画像を使用する
- ページが表示されたときにお知らせ画像も表示される高さにする

**Comment by tatsutakein** [comment]
> ページが表示されたときにお知らせ画像も表示される高さにする

画像にて補足いたします。

![CleanShot 2023-04-16 at 23 03 09](https://user-images.githubusercontent.com/19267812/232317162-ffef9681-4b1b-4b9e-9588-25540a8a2896.png)

**Comment by fcabs84** [comment]
@tatsutakein 
画像は以下を使用してください

**_PC_**
![fcpuentet_top_pc](https://user-images.githubusercontent.com/127853242/235382170-2b6ae51e-2fe2-4dfb-9498-f0105975ceaf.jpg)

**_モバイル_**
![fcpuentet_top_mobile](https://user-images.githubusercontent.com/127853242/235382182-dfeb766d-6078-4c2f-a0b7-31a7b9c455d0.jpg)
