### ISSUE TITLE
[FR]: トップページにリーグ戦予定/試合結果/活動予定の画像追加

### ISSUE THREAD

**Issue by fcabs84** [fcpuentet/fcpuentet-frontend#306]
### 既存の課題がありませんか？

- [X] 既存の課題を検索してみました

### 問題を説明する

タイムリーな情報発信のため、定期的に更新できるリーグ戦予定、試合結果、活動予定ページが必要。

### 解決策を説明する

将来的には更新ページとして用意したいが、取り急ぎトップページに画像を掲載する形で対応したい。
画像は定期的に更新できるようにする。

`NEWS`と`SOCIAL`の間に以下画像を掲載。

`SCHEDULE`
<img width="683" alt="schedule_league" src="https://user-images.githubusercontent.com/127853242/235450356-186910f3-4479-4713-90d8-aa2b8aa4a355.png">

<img width="669" alt="ranking" src="https://user-images.githubusercontent.com/127853242/235450375-a9803e10-740e-467e-b9d0-ee5c3e3f2c38.png">

<img width="670" alt="schedule_event" src="https://user-images.githubusercontent.com/127853242/235450384-ffa75676-7e57-4179-9138-1849474bbae6.png">

**Comment by tatsutakein** [comment]
対応完了しました。
